name: "slither-action-foundry"
description: "Runs Slither, the Solidity static analyzer. Only supports Foundry projects."
inputs:
  solc-version:
    description: "The version of solc to use. Should be autodetected, but may be specified manually."
  node-version:
    description: "The version of node to use."
    default: 20
  target:
    description: "The path of the project that Slither should analyze, relative to the repo root."
    default: .
    type: string
  sarif:
    description: "If provided, the path of the SARIF file to produce, relative to the repo root."
  slither-args:
    description: "Extra arguments to pass to Slither."
  slither-config:
    description: "The path to the Slither configuration file. By default, `./slither.config.json` is used if present."
  slither-version:
    description: "The version of slither-analyzer to use. By default, the latest release in PyPI is used."
  slither-plugins:
    description: "A requirements.txt file to install alongside Slither. Useful to install custom plugins."
  ignore-compile:
    description: "Whether to ignore the compilation step when running crytic-compile and Slither."
    default: false
    type: boolean
  fail-on:
    description: "Cause the action to fail if Slither finds any findings of this severity or higher. By default it will fail if any finding is found"
    default: all
    type: string
  foundry-version:
    description: Commit hash for foundry to install
    default: 'dbc48ea'
    type: string
outputs:
  sarif:
    description: "If produced, the path of the SARIF file, relative to the repo root."
  stdout:
    description: "Standard output from Slither. Works well when passing `--checklist` in slither-args."
runs:
  using: composite

  steps:
    - name: Setup python
      uses: infra/cb-action-setup-python@master

    - name: Install solc-select
      shell: bash
      run: |
        pip3 install solc-select

    - name: Setup Node / Yarn
      uses: infra/cb-action-setup-node@master
      with:
        version: ${{ inputs.node-version }}

    - name: Setup foundry
      uses: infra/cb-action-setup-external-tool@master
      with:
        tool_name: 'foundry'
        version: '${{ inputs.foundry-version }}'

    - name: Run Slither Entrypoint Script
      shell: bash
      run: |
        ./.github/actions/slither-action/entrypoint.sh
      env:
        TARGET: ${{ inputs.target }}
        SOLCVER: ${{ inputs.solc_version }}
        NODEVER: ${{ inputs.node-version }}
        SARIFOUT: ${{ inputs.sarif }}
        SLITHERVER: ${{ inputs.slither-version }}
        SLITHERARGS: ${{ inputs.slither-args }}
        SLITHERCONF: ${{ inputs.slither-config }}
        SLITHERPLUGINS: ${{ inputs.slither-plugins }}
        STDOUTFILE: "/tmp/slither-stdout"
        IGNORECOMPILE: ${{ inputs.ignore-compile }}
        FAIL_ON_LEVEL: ${{ inputs.fail-on }}

branding:
  icon: "shield"
  color: "red"
